package controller;

public enum ResultType {
    DATE_INCORRECT,
    DATE_SUCCESS,
    INVALID_NUMBER,
    ADD_PERSON_SUCCESS,
    PERSON_EXISTED,
    PERSON_NOT_EXISTED,
    BANK_INVALID,
    BANK_EXITED,
    BANK_NOT_EXISTED,
    BANK_RECEIVER_NOT_EXISTED,
    BANK_SUCCESS,
    OPEN_ACCOUNT_SUCCESS,
    INVALID_TYPE,
    SET_PARAMETER_SUCCESS,
    INCOMPLETE_LOAN,
    ACCOUNT_NOT_EXISTED,
    ACCOUNT_RECEIVER_NOT_EXISTED,
    CLOSE_CURRENT_NOT_ALLOWED,
    CLOSE_ACCOUNT_SUCCESS,
    LOW_AGE,
    INVALID_CARD_NUMBER,
    INVALID_RECEIVER_CARD_NUMBER,
    INVALID_INPUT,
    INVALID_PASSWORD,
    INVALID_NEW_PASSWORD,
    PASSWORD2_SET,
    PASSWORD2_NOT_SET,
    ACCOUNT_DEPOSIT,
    ACCOUNT_CURRENT,
    RECEIVER_ACCOUNT_DEPOSIT,
    DEPOSIT_SUCCESS,
    EXTEND_SUCCESS,
    NOT_ALLOWED_MAX_AMOUNT_DAY,
    NOT_ENOUGH_BALANCE,
    NOT_ENOUGH_BALANCE_DEPOSIT,
    WITHDRAW_SUCCESS,
    WITHDRAW_SUCCESS_DEPOSIT,
    TRANSFER_SUCCESS,
    TRANSFER_SUCCESS_DEPOSIT,
    GET_BALANCE_SUCCESS,
    CARD_EXPIRED,
    LOAN_SUCCESS,
    BANKRUPT,
    BANKRUPT_RECEIVER,
    LOAN_NOT_EXISTED,
    LOAN_FINISH,
    PAY_LOAN_SUCCESS,
    CURRENT_LOAN,
    NOT_ALLOWED_PERSON,
    NOT_ALLOWED_PERSON_RECEIVER;

    private String value;

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
